<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MySetLib\MySetLib.csproj" />
    <ProjectReference Include="..\MySetProject\MySetProject\MySetProject.csproj" />
  </ItemGroup>

</Project>
